In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('../Base_Dataset/OER cost savings spring 2023 (2).xlsx', sheet_name="Summer 2020")
df

,Course #,Course name,Instructor,OER,Enrollment,Cost Savings ($)
0,ACCT:2100:0EXW,Introduction to Financial Accounting,Moss,Learn Accounting for Free,33.0,NaN
1,PHYS:1611,Introductory Physics 1,Wetzel,OpenStax Physics,NaN,0.00
2,SSW:3700:0EXW,Intro to Trauma and Resilience,Farley,Trauma Informed Care document from SAMSHA,49.0,5730.06
3,SSW:3700:0EXT,Intro to Trauma and Resilience,Farley,Trauma Informed Care document from SAMSHA,41.0,4794.54
4,SSW:3840:0EXV,Human Behavior in the Social Environment,Cummings,Human Behavior in the Social Environment,17.0,1987.98
5,SSW:3840:0EXW,Human Behavior in the Social Environment,Cummings,Human Behavior in the Social Environment,24.0,2806.56

In [7]:
phrases = [
    "EDTL",
    "COMM",
    "GEOG",
    "ITAL",
    "BIOS",
    "NURS",
    "MGMT",
    "SPAN",
    "RUSS",
    "SSW",
    "CSD",
    "MED",
    "KORE",
    "ARAB",
    "CS",
    "MATH",
    "MUSM",
    "POLI",
    "SWAH",
    "SLIS",
    "ANTH",
    "ECON",
    "PCOL",
    "ESL",
    "PHAR",
    "MICR",
    "MUSM",
    "ACCT",
    "SOC",
    "RCE",
    "ECE",
    "CLSA",
    "JMC",
    "PHYS",
    
]


assigned_value = [
    "Education",
    "Communication",
    "Geographical and Sustainablilty Sciences",
    "French and Italian",
    "Biostatistics",
    "College of Nursing",
    "Management and Entrepreneurship",
    "Spanish and Portuguese",
    "Russian",
    "School of Social Work",
    "Communication Sciences and Disorders",
    "Carver College of Medicine",
    "Asian & Slavic Languages and Literatures",
    "Arabic Language and Literature",
    "Computer Science",
    "Mathematics",
    "Museum Studies",
    "Political Science",
    "Swahili",
    "Library and Information Science",
    "Anthropology",
    "Economics",
    "Neuroscience and Pharamcology",
    "English as a Second Language Programs",
    "College of Pharmacy",
    "Microbiology and Immunology",
    "Museum Studies",
    "Accounting",
    "Sociology and Criminology",
    "Department of Counselor Education" ,
    "Electrical and Computer Engineering",
    "Classics",
    "School of Journalism and Mass Communication",
    "Physics and Astronomy"
]


conditions = [df["Course #"].str.contains(phrase, na=False) for phrase in phrases]

default_value = "None"

df["Department"] = np.select(conditions, assigned_value, default_value)

In [8]:
df

,Course #,Course name,Instructor,OER,Enrollment,Cost Savings ($),Department
0,ACCT:2100:0EXW,Introduction to Financial Accounting,Moss,Learn Accounting for Free,33.0,NaN,Accounting
1,PHYS:1611,Introductory Physics 1,Wetzel,OpenStax Physics,NaN,0.00,Physics and Astronomy
2,SSW:3700:0EXW,Intro to Trauma and Resilience,Farley,Trauma Informed Care document from SAMSHA,49.0,5730.06,School of Social Work
3,SSW:3700:0EXT,Intro to Trauma and Resilience,Farley,Trauma Informed Care document from SAMSHA,41.0,4794.54,School of Social Work
4,SSW:3840:0EXV,Human Behavior in the Social Environment,Cummings,Human Behavior in the Social Environment,17.0,1987.98,School of Social Work
5,SSW:3840:0EXW,Human Behavior in the Social Environment,Cummings,Human Behavior in the Social Environment,24.0,2806.56,School of Social Work

In [9]:
df.fillna({"Cost Savings ($)": 3859.02}, inplace=True)

In [10]:
df

,Course #,Course name,Instructor,OER,Enrollment,Cost Savings ($),Department
0,ACCT:2100:0EXW,Introduction to Financial Accounting,Moss,Learn Accounting for Free,33.0,3859.02,Accounting
1,PHYS:1611,Introductory Physics 1,Wetzel,OpenStax Physics,NaN,0.00,Physics and Astronomy
2,SSW:3700:0EXW,Intro to Trauma and Resilience,Farley,Trauma Informed Care document from SAMSHA,49.0,5730.06,School of Social Work
3,SSW:3700:0EXT,Intro to Trauma and Resilience,Farley,Trauma Informed Care document from SAMSHA,41.0,4794.54,School of Social Work
4,SSW:3840:0EXV,Human Behavior in the Social Environment,Cummings,Human Behavior in the Social Environment,17.0,1987.98,School of Social Work
5,SSW:3840:0EXW,Human Behavior in the Social Environment,Cummings,Human Behavior in the Social Environment,24.0,2806.56,School of Social Work

In [11]:
df.fillna({"Enrollment": 0}, inplace=True)

In [12]:
df

,Course #,Course name,Instructor,OER,Enrollment,Cost Savings ($),Department
0,ACCT:2100:0EXW,Introduction to Financial Accounting,Moss,Learn Accounting for Free,33.0,3859.02,Accounting
1,PHYS:1611,Introductory Physics 1,Wetzel,OpenStax Physics,0.0,0.00,Physics and Astronomy
2,SSW:3700:0EXW,Intro to Trauma and Resilience,Farley,Trauma Informed Care document from SAMSHA,49.0,5730.06,School of Social Work
3,SSW:3700:0EXT,Intro to Trauma and Resilience,Farley,Trauma Informed Care document from SAMSHA,41.0,4794.54,School of Social Work
4,SSW:3840:0EXV,Human Behavior in the Social Environment,Cummings,Human Behavior in the Social Environment,17.0,1987.98,School of Social Work
5,SSW:3840:0EXW,Human Behavior in the Social Environment,Cummings,Human Behavior in the Social Environment,24.0,2806.56,School of Social Work

In [13]:
df.to_csv('summer_2020.csv')